spring.application.name=veterinaria
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/veterinaria_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.servlet.session.cookie.name=VET_SESSION_ID
server.servlet.session.timeout=70m

spring.thymeleaf.cache=false

logging.level.org.springframework.security=INFO
logging.level.com.clinica_veterinaria.veterinaria=DEBUG
